import { RefList } from '../models/ref-list';

export enum FeatureCodes {
  setting = 'setting',
  countries = 'countries',
  administration = 'administration',
  company = 'company',
  companies = 'companies',
  features = 'features',
  groups = 'groups',
  users = 'users',
  paramProject = 'param-project',
  userpackages = 'userpackages',
  calendar = 'calendar',

  account = 'account',
  profile = 'profile',
  userFeatures = 'user-features',
  packages = 'packages',
  animals = 'animals',
  pickup = 'pickup',
  picked = 'picked',
  collect = 'collect',
  stock = 'stock',
  delivery = 'delivery',
  road = 'road',
  finance = 'finance',
}

export const listFeatureActions: RefList<FeatureCodes>[] = [
  { key: FeatureCodes.setting, value: 'Setting' },
  { key: FeatureCodes.countries, value: 'Countries' },
  { key: FeatureCodes.administration, value: 'Administration' },
  { key: FeatureCodes.company, value: 'Company' },
  { key: FeatureCodes.companies, value: 'Companies' },
  { key: FeatureCodes.features, value: 'Features' },
  { key: FeatureCodes.groups, value: 'Groups' },
  { key: FeatureCodes.users, value: 'Users' },
  { key: FeatureCodes.paramProject, value: 'Params Project' },
  { key: FeatureCodes.userpackages, value: 'User Packages' },
  { key: FeatureCodes.account, value: 'Account' },
  { key: FeatureCodes.profile, value: 'Profile' },
  { key: FeatureCodes.animals, value: 'Animals' },
  { key: FeatureCodes.userFeatures, value: 'user-features' },
  { key: FeatureCodes.packages, value: 'packages' },
  { key: FeatureCodes.pickup, value: 'pickup' },
  { key: FeatureCodes.stock, value: 'stock' },
  { key: FeatureCodes.collect, value: 'collect' },
  { key: FeatureCodes.delivery, value: 'delivery' },
  { key: FeatureCodes.road, value: 'road' },
  { key: FeatureCodes.finance, value: 'finance' },
  { key: FeatureCodes.calendar, value: 'calendar' },
  { key: FeatureCodes.picked, value: 'picked packages' },
];
